name: selfrecon
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=36.0.2=py39hd97740a_1
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.10=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_16
  - libiconv=1.16=h516909a_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=14.0.3=he0ac6c6_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - numpy=1.21.5=py39he7a7128_2
  - numpy-base=1.21.5=py39hf524024_2
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1o=h166bdaf_0
  - pillow=9.1.0=py39hae2aec6_2
  - pip=22.0.4=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.12=h9a8a25e_1_cpython
  - python_abi=3.9=2_cp39
  - pytorch=1.11.0=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - setuptools=62.1.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.5=h4ff8645_0
  - tbb=2021.5.0=h924138e_1
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.11.0=py39_cu102
  - torchvision=0.12.0=py39_cu102
  - tzdata=2022a=h191b570_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==0.12.0
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - astunparse==1.6.3
    - attrs==21.4.0
    - babel==2.10.1
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - cachetools==5.2.0
    - chex==0.1.5
    - cloudpickle==2.2.0
    - contextlib2==21.6.0
    - cvxpy==1.2.1
    - cycler==0.11.0
    - cython==0.29.33
    - debugpy==1.6.0
    - decorator==5.1.1
    - deepsplines==1.0.0
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - dm-tree==0.1.7
    - dsntnn==0.5.3
    - ecos==2.0.10
    - einops==0.4.1
    - entmax==1.0
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - flatbuffers==1.12
    - flax==0.3.4
    - fonttools==4.33.3
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.56.4
    - grpcio==1.34.1
    - h5py==3.1.0
    - hdf5storage==0.1.18
    - imageio==2.19.0
    - importlib-metadata==4.11.3
    - install==1.3.5
    - ipykernel==6.13.0
    - ipython==8.3.0
    - ipython-genutils==0.2.0
    - jacobian==1.0.0
    - jax==0.2.18
    - jaxlib==0.1.69
    - jedi==0.18.1
    - jinja2==3.1.2
    - json5==0.9.7
    - jsonschema==4.5.1
    - jupyter-client==7.3.0
    - jupyter-core==4.10.0
    - jupyter-server==1.17.0
    - jupyterlab==3.4.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.13.0
    - keras==2.9.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - libclang==14.0.1
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - ml-collections==0.1.0
    - mosek==9.3.20
    - mrrt-mri==0.3.4
    - mrrt-nufft==0.2.2
    - mrrt-operators==0.2.1
    - mrrt-utils==0.2.2
    - msgpack==1.0.4
    - nbclassic==0.3.7
    - nbclient==0.6.2
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8
    - notebook==6.4.11
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - odl==0.7.0
    - opencv-contrib-python==4.6.0.66
    - opt-einsum==3.3.0
    - optax==0.0.9
    - osqp==0.6.2.post5
    - packaging==21.3
    - pandas==1.5.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - piq==0.7.0
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.29
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptwt==0.1.4.post1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.12.0
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytorch-model-summary==0.1.2
    - pytorch-msssim==0.2.1
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyzmq==22.3.0
    - qdldl==0.1.5.post2
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-image==0.19.2
    - scipy==1.8.0
    - scs==3.2.0
    - seaborn==0.12.1
    - send2trash==1.8.0
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.5.0
    - tensorflow-addons==0.13.0
    - tensorflow-datasets==4.3.0
    - tensorflow-estimator==2.5.0
    - tensorflow-gan==2.0.0
    - tensorflow-hub==0.12.0
    - tensorflow-io==0.18.0
    - tensorflow-io-gcs-filesystem==0.18.0
    - tensorflow-metadata==1.10.0
    - tensorflow-probability==0.13.0
    - termcolor==1.1.0
    - terminado==0.13.3
    - tifffile==2022.5.4
    - timm==0.5.4
    - tinycss2==1.1.1
    - toolz==0.12.0
    - torchkbnufft==1.3.0
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.1.1
    - typeguard==2.13.3
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2
    - werkzeug==2.1.2
    - wrapt==1.12.1
    - x-transformers==0.27.2
    - zipp==3.8.0

